import { completeFromList, snippetCompletion, type CompletionSource } from "@codemirror/autocomplete";

const shellSnippets = [
  snippetCompletion("if ${};\nthen\n\t${}\nfi", { label: "if", detail: "statement", type: "keyword" }),
  snippetCompletion("for ${name} in ${list};\ndo\n\t${}\ndone", { label: "for", detail: "loop", type: "keyword" }),
  snippetCompletion("while ${};\ndo\n\t${}\ndone", { label: "while", detail: "loop", type: "keyword" }),
  snippetCompletion("case ${} in\n\t${pattern})\n\t\t${} ;;\nesac", { label: "case", detail: "statement", type: "keyword" }),
  snippetCompletion("function ${name} {\n\t${}\n}", { label: "function", detail: "definition", type: "keyword" }),
];

const shellKeywords = [
  { label: "if", detail: "fi", type: "keyword", apply: "if " },
  { label: "then", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "elif", type: "keyword" },
  { label: "fi", type: "keyword" },
  { label: "for", type: "keyword", apply: "for " },
  { label: "while", type: "keyword", apply: "while " },
  { label: "do", type: "keyword" },
  { label: "done", type: "keyword" },
  { label: "case", type: "keyword", apply: "case " },
  { label: "esac", type: "keyword" },
  { label: "function", type: "keyword", apply: "function " },
  { label: "return", type: "keyword" },
  { label: "exit", type: "keyword" },
  { label: "export", type: "keyword" },
  { label: "local", type: "keyword" },
  { label: "readonly", type: "keyword" },
  { label: "unset", type: "keyword" },
  { label: "declare", type: "keyword" },
  { label: "typeset", type: "keyword" },
  { label: "echo", type: "keyword" },
  { label: "printf", type: "keyword" },
  { label: "read", type: "keyword" },
  { label: "source", type: "keyword" },
  { label: "alias", type: "keyword" },
  { label: "unalias", type: "keyword" },
  { label: "cd", type: "keyword" },
  { label: "pwd", type: "keyword" },
  { label: "ls", type: "keyword" },
  { label: "mkdir", type: "keyword" },
  { label: "rmdir", type: "keyword" },
  { label: "rm", type: "keyword" },
  { label: "cp", type: "keyword" },
  { label: "mv", type: "keyword" },
  { label: "cat", type: "keyword" },
  { label: "grep", type: "keyword" },
  { label: "sed", type: "keyword" },
  { label: "awk", type: "keyword" },
  { label: "find", type: "keyword" },
  { label: "chmod", type: "keyword" },
  { label: "chown", type: "keyword" },
  { label: "ps", type: "keyword" },
  { label: "kill", type: "keyword" },
  { label: "test", type: "keyword", detail: "[ ]" },
  { label: "exec", type: "keyword" },
  { label: "trap", type: "keyword" },
];

const shellCompletions = completeFromList([...shellSnippets, ...shellKeywords]);

const goSnippets = [
  snippetCompletion("func ${name}(${params}) ${type} {\n\t${}\n}", { label: "func", detail: "definition", type: "keyword" }),
  snippetCompletion("for ${} {\n\t${}\n}", { label: "for", detail: "loop", type: "keyword" }),
  snippetCompletion("if ${} {\n\t${}\n}", { label: "if", detail: "block", type: "keyword" }),
  snippetCompletion("if ${} {\n\t${}\n} else {\n\t${}\n}", { label: "if", detail: "/ else block", type: "keyword" }),
  snippetCompletion("switch ${} {\ncase ${}:\n\t${}\n}", { label: "switch", detail: "statement", type: "keyword" }),
  snippetCompletion("type ${name} struct {\n\t${}\n}", { label: "struct", detail: "definition", type: "keyword" }),
  snippetCompletion("type ${name} interface {\n\t${}\n}", { label: "interface", detail: "definition", type: "keyword" }),
];

const goKeywords = [
  { label: "package", type: "keyword", apply: "package " },
  { label: "import", type: "keyword", apply: "import " },
  { label: "func", type: "keyword", apply: "func " },
  { label: "return", type: "keyword" },
  { label: "var", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "type", type: "keyword", apply: "type " },
  { label: "struct", type: "keyword" },
  { label: "interface", type: "keyword" },
  { label: "map", type: "keyword", apply: "map[" },
  { label: "chan", type: "keyword" },
  { label: "if", type: "keyword", apply: "if " },
  { label: "else", type: "keyword" },
  { label: "for", type: "keyword", apply: "for " },
  { label: "range", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "goto", type: "keyword" },
  { label: "defer", type: "keyword" },
  { label: "go", type: "keyword" },
  { label: "select", type: "keyword" },
  { label: "fallthrough", type: "keyword" },
  { label: "nil", type: "keyword" },
  { label: "true", type: "keyword" },
  { label: "false", type: "keyword" },
  { label: "int", type: "type" },
  { label: "int8", type: "type" },
  { label: "int16", type: "type" },
  { label: "int32", type: "type" },
  { label: "int64", type: "type" },
  { label: "uint", type: "type" },
  { label: "uint8", type: "type" },
  { label: "uint16", type: "type" },
  { label: "uint32", type: "type" },
  { label: "uint64", type: "type" },
  { label: "float32", type: "type" },
  { label: "float64", type: "type" },
  { label: "bool", type: "type" },
  { label: "string", type: "type" },
  { label: "byte", type: "type" },
  { label: "rune", type: "type" },
  { label: "error", type: "type" },
  { label: "append", type: "function" },
  { label: "len", type: "function" },
  { label: "cap", type: "function" },
  { label: "copy", type: "function" },
  { label: "delete", type: "function" },
  { label: "make", type: "function" },
  { label: "new", type: "function" },
  { label: "close", type: "function" },
  { label: "panic", type: "function" },
  { label: "recover", type: "function" },
  { label: "print", type: "function" },
  { label: "println", type: "function" },
];

const goCompletions = completeFromList([...goSnippets, ...goKeywords]);

const cppSnippets = [
  snippetCompletion("for (int ${i} = 0; ${i} < ${n}; ${i}++) {\n\t${}\n}", { label: "for", detail: "loop", type: "keyword" }),
  snippetCompletion("while (${}) {\n\t${}\n}", { label: "while", detail: "loop", type: "keyword" }),
  snippetCompletion("if (${}) {\n\t${}\n}", { label: "if", detail: "block", type: "keyword" }),
  snippetCompletion("if (${}) {\n\t${}\n} else {\n\t${}\n}", { label: "if", detail: "/ else block", type: "keyword" }),
  snippetCompletion("class ${name} {\npublic:\n\t${name}(${params});\n\t~${name}();\n\nprivate:\n\t${}\n};", { label: "class", detail: "definition", type: "keyword" }),
  snippetCompletion("struct ${name} {\n\t${}\n};", { label: "struct", detail: "definition", type: "keyword" }),
];

const cppKeywords = [
  { label: "if", type: "keyword", apply: "if " },
  { label: "else", type: "keyword" },
  { label: "for", type: "keyword", apply: "for " },
  { label: "while", type: "keyword", apply: "while " },
  { label: "do", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "goto", type: "keyword" },
  { label: "struct", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "enum", type: "keyword" },
  { label: "union", type: "keyword" },
  { label: "typedef", type: "keyword" },
  { label: "namespace", type: "keyword" },
  { label: "using", type: "keyword" },
  { label: "template", type: "keyword" },
  { label: "typename", type: "keyword" },
  { label: "public", type: "keyword" },
  { label: "private", type: "keyword" },
  { label: "protected", type: "keyword" },
  { label: "virtual", type: "keyword" },
  { label: "override", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "extern", type: "keyword" },
  { label: "inline", type: "keyword" },
  { label: "explicit", type: "keyword" },
  { label: "friend", type: "keyword" },
  { label: "operator", type: "keyword" },
  { label: "new", type: "keyword" },
  { label: "delete", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "noexcept", type: "keyword" },
  { label: "int", type: "type" },
  { label: "long", type: "type" },
  { label: "short", type: "type" },
  { label: "float", type: "type" },
  { label: "double", type: "type" },
  { label: "char", type: "type" },
  { label: "bool", type: "type" },
  { label: "void", type: "type" },
  { label: "auto", type: "keyword" },
  { label: "sizeof", type: "keyword" },
  { label: "typedef", type: "keyword" },
  { label: "include", type: "keyword", apply: "#include " },
];

const cppCompletions = completeFromList([...cppSnippets, ...cppKeywords]);

const javaSnippets = [
  snippetCompletion("for (int ${i} = 0; ${i} < ${n}; ${i}++) {\n\t${}\n}", { label: "for", detail: "loop", type: "keyword" }),
  snippetCompletion("while (${}) {\n\t${}\n}", { label: "while", detail: "loop", type: "keyword" }),
  snippetCompletion("if (${}) {\n\t${}\n}", { label: "if", detail: "block", type: "keyword" }),
  snippetCompletion("if (${}) {\n\t${}\n} else {\n\t${}\n}", { label: "if", detail: "/ else block", type: "keyword" }),
  snippetCompletion("try {\n\t${}\n} catch (${Exception} e) {\n\t${}\n}", { label: "try", detail: "/ catch block", type: "keyword" }),
  snippetCompletion("class ${name} {\n\t${}\n}", { label: "class", detail: "definition", type: "keyword" }),
  snippetCompletion("public static void main(String[] ${args}) {\n\t${}\n}", { label: "main", detail: "method", type: "keyword" }),
];

const javaKeywords = [
  { label: "public", type: "keyword" },
  { label: "private", type: "keyword" },
  { label: "protected", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "final", type: "keyword" },
  { label: "abstract", type: "keyword" },
  { label: "synchronized", type: "keyword" },
  { label: "volatile", type: "keyword" },
  { label: "transient", type: "keyword" },
  { label: "native", type: "keyword" },
  { label: "strictfp", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "interface", type: "keyword" },
  { label: "enum", type: "keyword" },
  { label: "extends", type: "keyword" },
  { label: "implements", type: "keyword" },
  { label: "super", type: "keyword" },
  { label: "this", type: "keyword" },
  { label: "new", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "if", type: "keyword", apply: "if " },
  { label: "else", type: "keyword" },
  { label: "for", type: "keyword", apply: "for " },
  { label: "while", type: "keyword", apply: "while " },
  { label: "do", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "throws", type: "keyword" },
  { label: "import", type: "keyword", apply: "import " },
  { label: "package", type: "keyword", apply: "package " },
  { label: "int", type: "type" },
  { label: "long", type: "type" },
  { label: "short", type: "type" },
  { label: "byte", type: "type" },
  { label: "float", type: "type" },
  { label: "double", type: "type" },
  { label: "char", type: "type" },
  { label: "boolean", type: "type" },
  { label: "void", type: "type" },
  { label: "String", type: "type" },
  { label: "null", type: "keyword" },
  { label: "true", type: "keyword" },
  { label: "false", type: "keyword" },
  { label: "instanceof", type: "keyword" },
  { label: "assert", type: "keyword" },
];

const javaCompletions = completeFromList([...javaSnippets, ...javaKeywords]);

export function getLegacyCompletions(ext: string): CompletionSource | null {
  switch (ext) {
    case "sh": case "bash": case "zsh": return shellCompletions;
    case "go": return goCompletions;
    case "java": return javaCompletions;
    case "c": case "cpp": case "cc": case "cxx": case "h": case "hpp": return cppCompletions;
    default: return null;
  }
}
