export const Events = {
  CLOSE_POPUPS: "aurora-close-popups",
  FOCUS_TERMINAL_INPUT: "aurora-focus-terminal-input",
  TOGGLE_COMMAND_PALETTE: "toggle-command-palette",
  TOGGLE_AI_BAR: "toggle-ai-bar",
  FOCUS_COMMAND_LINE: "focus-command-line",
  CWD_CHANGE: "cwd-change",
  SHOW_CONTEXT_MENU: "show-context-menu",
  TERMINAL_CLEAR: "terminal-clear",
  TERMINAL_COPY: "terminal-copy",
  TERMINAL_SESSION_RESTART: "terminal-session-restart",
  SIDEBAR_OPEN_FILE: "sidebar-open-file",
  SIDEBAR_OPEN_IN_NEW_TAB: "sidebar-open-in-new-tab",
  FILE_SELECT_ALL: "file-select-all",
  FILE_PASTE: "file-paste",
  FILE_COPY_LINE: "file-copy-line",
  FILE_CUT_LINE: "file-cut-line",
  FILE_CUT_SELECTION: "file-cutter-selection",
  GIT_FILE_HISTORY: "git-file-history",
  SEARCH_DIR: "search-dir",
  FOCUS_SEARCH_BAR: "focus-search-bar",

  ptyCommandRun: (sessionId: string) => `pty-command-run:${sessionId}`,
  ptySessionData: (sessionId: string) => `pty-session-data:${sessionId}`,
  ptySessionExit: (sessionId: string) => `pty-session-exit:${sessionId}`,
  aiChunk: (id: string) => `ai-chunk-${id}`,
  aiComplete: (id: string) => `ai-complete-${id}`,
};
